#!/usr/bin/env python3
"""Generate CrossVi's compact English-Vietnamese vocabulary table.

The eligible headwords come from the Oxford 3000 PDF supplied for CrossVi,
plus a small curated set of essential grammatical forms such as ``are`` and
``was``. ``wordfreq`` is used only to rank that trusted pool and select exactly
3,000 single-word entries. Definitions and pronunciations prefer
thichhoc-dict and fall back to the corresponding PDF row. Closed-class words
are curated here because WordNet-based dictionaries do not represent their
everyday grammatical senses well.

Data generated by this script is a modified derivative of thichhoc-dict and is
licensed CC BY-SA 4.0. The firmware shows the required attribution in the
Vocabulary activity.
"""

from __future__ import annotations

import argparse
import glob
import json
import re
import subprocess
from pathlib import Path

try:
    from wordfreq import top_n_list
except ImportError as exc:  # pragma: no cover - developer-only tool
    raise SystemExit("Install the developer dependency with: pip install wordfreq") from exc

try:
    import pdfplumber
except ImportError as exc:  # pragma: no cover - developer-only tool
    raise SystemExit("Install the developer dependency with: pip install pdfplumber") from exc


ENTRY_COUNT = 3000
SOURCE_REVISION = "8be4c048f389fd33f6d6d3d14f2350a1a9c3969a"
WORD_LIST_SOURCE = "https://english4u.com.vn/Uploads/files/3000.pdf"
POS = {"noun": 0, "verb": 1, "adjective": 2, "adj": 2, "adverb": 3, "adv": 3, "other": 4}

# word: (IPA, Vietnamese meaning, POS). These are short, original glosses for
# grammatical/common senses absent from WordNet or easily confused with an
# abbreviation (for example "it" = information technology).
OVERRIDES = {
    "a": ("/ə/", "một; một người hoặc vật", "other"),
    "an": ("/ən/", "một; một người hoặc vật", "other"),
    "am": ("/æm/", "là; thì; ở", "verb"),
    "and": ("/ænd/", "và", "other"),
    "are": ("/ɑr/", "là; thì; ở", "verb"),
    "as": ("/æz/", "như; với tư cách là", "other"),
    "at": ("/æt/", "tại; ở", "other"),
    "be": ("/bi/", "là; thì; ở", "verb"),
    "because": ("/bɪˈkɔz/", "bởi vì", "other"),
    "been": ("/bɪn/", "đã từng; đã ở", "verb"),
    "being": ("/ˈbiɪŋ/", "đang là; sự tồn tại", "verb"),
    "but": ("/bʌt/", "nhưng", "other"),
    "by": ("/baɪ/", "bởi; bằng; cạnh", "other"),
    "can": ("/kæn/", "có thể", "verb"),
    "cd": ("/ˌsiːˈdiː/", "đĩa CD", "noun"),
    "could": ("/kʊd/", "có thể; đã có thể", "verb"),
    "did": ("/dɪd/", "đã làm", "verb"),
    "do": ("/du/", "làm; thực hiện", "verb"),
    "does": ("/dʌz/", "làm; thực hiện", "verb"),
    "dressed": ("/drɛst/", "đã mặc quần áo", "adjective"),
    "for": ("/fɔr/", "cho; để; vì", "other"),
    "from": ("/frʌm/", "từ", "other"),
    "had": ("/hæd/", "đã có; đã sở hữu", "verb"),
    "has": ("/hæz/", "có; sở hữu", "verb"),
    "have": ("/hæv/", "có; sở hữu", "verb"),
    "he": ("/hi/", "anh ấy; ông ấy", "other"),
    "her": ("/hɝ/", "cô ấy; của cô ấy", "other"),
    "him": ("/hɪm/", "anh ấy; ông ấy", "other"),
    "his": ("/hɪz/", "của anh ấy", "other"),
    "how": ("/haʊ/", "như thế nào", "other"),
    "if": ("/ɪf/", "nếu", "other"),
    "i": ("/aɪ/", "tôi", "other"),
    "in": ("/ɪn/", "trong; ở trong", "other"),
    "is": ("/ɪz/", "là; thì; ở", "verb"),
    "it": ("/ɪt/", "nó; điều đó", "other"),
    "its": ("/ɪts/", "của nó", "other"),
    "may": ("/meɪ/", "có thể", "verb"),
    "me": ("/mi/", "tôi; cho tôi", "other"),
    "might": ("/maɪt/", "có thể; có lẽ", "verb"),
    "ms": ("/mɪz/", "bà; cô (cách xưng hô)", "noun"),
    "must": ("/mʌst/", "phải; chắc hẳn", "verb"),
    "my": ("/maɪ/", "của tôi", "other"),
    "no": ("/noʊ/", "không; không có", "other"),
    "not": ("/nɑt/", "không", "adv"),
    "of": ("/əv/", "của", "other"),
    "on": ("/ɑn/", "trên; ở trên", "other"),
    "or": ("/ɔr/", "hoặc", "other"),
    "our": ("/aʊr/", "của chúng tôi; của chúng ta", "other"),
    "she": ("/ʃi/", "cô ấy; bà ấy", "other"),
    "should": ("/ʃʊd/", "nên; cần", "verb"),
    "than": ("/ðæn/", "hơn; so với", "other"),
    "that": ("/ðæt/", "đó; rằng; cái mà", "other"),
    "the": ("/ðə/", "mạo từ chỉ người hoặc vật đã biết", "other"),
    "their": ("/ðɛr/", "của họ", "other"),
    "them": ("/ðɛm/", "họ; chúng", "other"),
    "there": ("/ðɛr/", "ở đó; có", "other"),
    "these": ("/ðiz/", "những người hoặc vật này", "other"),
    "they": ("/ðeɪ/", "họ; chúng", "other"),
    "this": ("/ðɪs/", "này; điều này", "other"),
    "those": ("/ðoʊz/", "những người hoặc vật kia", "other"),
    "to": ("/tu/", "đến; tới; để", "other"),
    "us": ("/ʌs/", "chúng tôi; chúng ta", "other"),
    "was": ("/wʌz/", "đã là; đã ở", "verb"),
    "we": ("/wi/", "chúng tôi; chúng ta", "other"),
    "were": ("/wɝ/", "đã là; đã ở", "verb"),
    "what": ("/wʌt/", "gì; điều gì", "other"),
    "when": ("/wɛn/", "khi; lúc nào", "other"),
    "which": ("/wɪtʃ/", "nào; cái mà", "other"),
    "who": ("/hu/", "ai; người mà", "other"),
    "will": ("/wɪl/", "sẽ", "verb"),
    "with": ("/wɪð/", "với; cùng với", "other"),
    "would": ("/wʊd/", "sẽ; muốn (trong giả định)", "verb"),
    "you": ("/ju/", "bạn; các bạn", "other"),
    "your": ("/jʊr/", "của bạn; của các bạn", "other"),
}


def first_meaning(senses: object) -> str:
    if not isinstance(senses, list) or not senses:
        return ""
    value = senses[0]
    if isinstance(value, dict):
        value = value.get("definition_vi") or value.get("gloss_vi") or ""
    return " ".join(str(value).split())


def utf8_prefix(value: str, max_bytes: int) -> str:
    data = value.encode("utf-8")
    if len(data) <= max_bytes:
        return value
    data = data[:max_bytes]
    while data and (data[-1] & 0xC0) == 0x80:
        data = data[:-1]
    return data.decode("utf-8", errors="ignore").rstrip(" ,;:-")


def entry_priority(entry: dict) -> tuple[int, int, int]:
    # A larger WordNet tag count means the sense/POS is seen more often.
    raw_tag = entry.get("extra", {}).get("tag", 0)
    try:
        tag = int(raw_tag)
    except (TypeError, ValueError):
        tag = 0
    pos_preference = {"n": 3, "v": 2, "adj": 1, "adv": 0}.get(entry.get("pos"), -1)
    return (tag, pos_preference, -len(first_meaning(entry.get("senses_vi"))))


def load_dictionary(root: Path) -> dict[str, dict]:
    best: dict[str, dict] = {}
    pattern = str(root / "dict-en-vi" / "data" / "entries" / "*.jsonl")
    for filename in glob.glob(pattern):
        with open(filename, encoding="utf-8") as stream:
            for line in stream:
                entry = json.loads(line)
                word = entry.get("headword", "")
                if not re.fullmatch(r"[a-z]+", word):
                    continue
                # Entries without an LLM confidence marker come directly from
                # the source dictionaries. Only explicitly medium/low generated
                # entries are excluded from the preferred path.
                if entry.get("extra", {}).get("llm_confidence") not in (None, "high"):
                    continue
                if not (entry.get("pron") or "").strip() or not first_meaning(entry.get("senses_vi")):
                    continue
                if word not in best or entry_priority(entry) > entry_priority(best[word]):
                    best[word] = entry
    return best


def canonical_headword(value: str) -> str:
    value = value.lower().replace("’", "'").strip(" .")
    value = re.sub(r"\s*\([^)]*\)\s*", " ", value).strip()
    value = value.split(",", 1)[0].strip().split("/", 1)[0].strip()
    words = value.split()
    # A few rows in this old PDF visually join the Type column to Word.
    type_words = {
        "n",
        "v",
        "adj",
        "adv",
        "prep",
        "pron",
        "det",
        "conj",
        "modal",
        "number",
        "pro",
        "prefix",
        "exclamation",
    }
    while len(words) > 1 and words[-1] in type_words:
        words.pop()
    value = " ".join(words)
    return value if re.fullmatch(r"[a-z]+", value) else ""


def pdf_part_of_speech(value: str) -> str:
    tokens = {token.strip() for token in value.lower().split(",")}
    if "n" in tokens:
        return "noun"
    if "v" in tokens:
        return "verb"
    if "adj" in tokens:
        return "adjective"
    if "adv" in tokens:
        return "adverb"
    return "other"


def load_common_word_pdf(path: Path) -> dict[str, tuple[str, str, str]]:
    settings = {
        "vertical_strategy": "explicit",
        "horizontal_strategy": "lines",
        "explicit_vertical_lines": [0, 34.5, 210, 303, 413, 595.4],
        "snap_tolerance": 3,
        "join_tolerance": 3,
        "intersection_tolerance": 5,
    }
    entries: dict[str, tuple[str, str, str]] = {}
    with pdfplumber.open(path) as document:
        for page in document.pages:
            for table in page.extract_tables(settings):
                for row in table:
                    if len(row) < 5 or not row[0]:
                        continue
                    number = "".join(row[0].split())
                    if not number.isdigit() or not 1 <= int(number) <= 3396:
                        continue
                    word = canonical_headword(" ".join((row[1] or "").split()))
                    if not word:
                        continue
                    part = pdf_part_of_speech(" ".join((row[2] or "").split()))
                    pronunciation = " ".join((row[3] or "").split())
                    meaning = " ".join((row[4] or "").split())
                    entries.setdefault(word, (pronunciation, meaning, part))
    if len(entries) < ENTRY_COUNT:
        raise SystemExit(f"Only extracted {len(entries)} usable words from {path}")
    return entries


def normalize_pronunciation(value: str) -> str:
    value = "".join(value.split())
    value = (
        value.replace("'", "ˈ")
        .replace("´", "ˈ")
        .replace(",", "ˌ")
        .replace(":", "ː")
        .replace("з", "ɜ")
        .replace("З", "ɜ")
        .replace("ɳ", "ŋ")
        .replace("η", "ŋ")
        .replace("¸", "")
    )
    if value and not value.startswith("/"):
        value = f"/{value}/"
    return value


def cpp_string(value: str) -> str:
    encoded = json.dumps(value, ensure_ascii=False)
    return encoded[:-1] + r"\0" + encoded[-1]


def generate(dictionary_root: Path, word_list_pdf: Path, output: Path) -> None:
    revision = subprocess.check_output(
        ["git", "-C", str(dictionary_root), "rev-parse", "HEAD"], text=True
    ).strip()
    if revision != SOURCE_REVISION:
        raise SystemExit(f"Expected thichhoc-dict {SOURCE_REVISION}, found {revision}")

    dictionary = load_dictionary(dictionary_root)
    pdf_entries = load_common_word_pdf(word_list_pdf)
    eligible_words = set(pdf_entries) | set(OVERRIDES)
    ranked_words = [word for word in top_n_list("en", 20000) if word in eligible_words]
    if len(ranked_words) < ENTRY_COUNT:
        raise SystemExit(f"Only ranked {len(ranked_words)} eligible common words")

    entries: list[tuple[str, str, str, int]] = []
    for word in ranked_words[:ENTRY_COUNT]:
        if word in OVERRIDES:
            ipa, meaning, pos = OVERRIDES[word]
        else:
            entry = dictionary.get(word)
            if entry is not None:
                ipa = (entry.get("pron") or "").strip()
                meaning = first_meaning(entry.get("senses_vi"))
                pos = {"n": "noun", "v": "verb", "adj": "adjective", "adv": "adverb"}.get(
                    entry.get("pos"), "other"
                )
            else:
                ipa, meaning, pos = pdf_entries[word]
        ipa = normalize_pronunciation(ipa)
        meaning = utf8_prefix(meaning, 92)
        ipa = utf8_prefix(ipa, 48)
        if not ipa or not meaning:
            raise SystemExit(f"Missing pronunciation or meaning for selected word: {word}")
        entries.append((word, ipa, meaning, POS[pos]))

    if len(entries) != ENTRY_COUNT:
        raise SystemExit(f"Only found {len(entries)} eligible entries")

    offsets: list[int] = []
    offset = 0
    for word, ipa, meaning, _ in entries:
        offsets.append(offset)
        offset += sum(len(value.encode("utf-8")) + 1 for value in (word, ipa, meaning))

    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write("// Generated by scripts/generate_vocabulary_data.py. Do not edit.\n")
        stream.write("// Common-word list: " + WORD_LIST_SOURCE + "\n")
        stream.write("// Definitions derivative: thichhoc-dict @ " + SOURCE_REVISION + ", CC BY-SA 4.0.\n")
        stream.write("#pragma once\n#include <cstddef>\n#include <cstdint>\n\n")
        stream.write("namespace crossvi::vocabulary::generated {\n")
        stream.write(f"inline constexpr size_t ENTRY_COUNT = {len(entries)};\n")
        stream.write("inline constexpr char DATA[] =\n")
        for word, ipa, meaning, _ in entries:
            stream.write(f"    {cpp_string(word)} {cpp_string(ipa)} {cpp_string(meaning)}\n")
        stream.write("    ;\n\n")
        stream.write("inline constexpr uint32_t OFFSETS[ENTRY_COUNT] = {\n    ")
        for index, value in enumerate(offsets):
            stream.write(f"{value},")
            if (index + 1) % 16 == 0 and index + 1 != len(offsets):
                stream.write("\n    ")
            elif index + 1 != len(offsets):
                stream.write(" ")
        stream.write("\n};\n\ninline constexpr uint8_t PARTS_OF_SPEECH[ENTRY_COUNT] = {\n    ")
        for index, entry in enumerate(entries):
            stream.write(f"{entry[3]},")
            if (index + 1) % 32 == 0 and index + 1 != len(entries):
                stream.write("\n    ")
            elif index + 1 != len(entries):
                stream.write(" ")
        stream.write("\n};\n}\n")

    print(f"Generated {len(entries)} entries, {offset} bytes of UTF-8 data: {output}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dictionary", type=Path, required=True, help="Path to a thichhoc-dict checkout")
    parser.add_argument("--word-list-pdf", type=Path, required=True, help="Path to the supplied Oxford 3000 PDF")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("src/vocabulary/VocabularyData.generated.h"),
    )
    args = parser.parse_args()
    generate(args.dictionary.resolve(), args.word_list_pdf.resolve(), args.output)


if __name__ == "__main__":
    main()
