"""Generate one environment-local CrossVi version header for version.cpp."""

from __future__ import annotations

import configparser
import os
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(globals().get("__file__", Path.cwd() / "scripts" / "git_branch.py")).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from write_if_changed import write_if_changed


def warn(message: str) -> None:
    print(f"WARNING [git_branch.py]: {message}", file=sys.stderr)


def _safe(value: str) -> str:
    return "".join(character for character in value if character not in '"\\')


def _git(project_dir: str, arguments: list[str], label: str) -> str:
    try:
        return _safe(
            subprocess.check_output(
                ["git", *arguments], text=True, stderr=subprocess.PIPE, cwd=project_dir
            ).strip()
        )
    except (FileNotFoundError, subprocess.CalledProcessError, OSError) as error:
        warn(f"could not read git {label}: {error}; using unknown")
        return "unknown"


def base_version(project_dir: str) -> str:
    config = configparser.ConfigParser()
    config.read(os.path.join(project_dir, "platformio.ini"))
    return config.get("crosspoint", "version", fallback="0.0.0")


def compute_version(environment: str, project_dir: str) -> str:
    base = base_version(project_dir)
    if environment == "default":
        branch = _git(project_dir, ["rev-parse", "--abbrev-ref", "HEAD"], "branch")
        if branch == "HEAD":
            branch = "detached"
        sha = _git(project_dir, ["rev-parse", "--short", "HEAD"], "short SHA")
        return f"{base}-dev-{branch}-{sha}"
    if environment == "gh_release":
        return base
    if environment == "gh_release_rc":
        return f"{base}-rc+{_safe(os.environ.get('CROSSPOINT_RC_HASH', 'unknown'))}"
    if environment == "slim":
        return f"{base}-slim"
    if environment in ("simulator_x3", "simulator_x4"):
        return f"{base}-simulator"
    return f"{base}-{_safe(environment)}"


def generate(env) -> None:
    project_dir = env["PROJECT_DIR"]
    environment = env["PIOENV"]
    generated_dir = Path(env.subst("$BUILD_DIR")) / "generated"
    version = compute_version(environment, project_dir)
    header = generated_dir / "version.generated.h"
    write_if_changed(
        header,
        "#pragma once\n"
        "// Generated by scripts/git_branch.py.\n"
        f'#define CROSSVI_BUILD_VERSION "{version}"\n',
    )
    env.Append(CPPPATH=[str(generated_dir)])
    print(f"CrossVi build version: {version}")


try:
    Import("env")  # noqa: F821  # type: ignore[name-defined]
    generate(env)  # noqa: F821  # type: ignore[name-defined]
except NameError:
    if __name__ == "__main__":
        project = str(SCRIPT_DIR.parent)
        print(compute_version("default", project))
